-- setup-admin.sql
-- Supabase 管理员用户设置脚本

-- 1. 创建留言表
CREATE TABLE IF NOT EXISTS guestbook (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL,
  email TEXT,
  content TEXT NOT NULL,
  mood TEXT DEFAULT '😊',
  likes INTEGER DEFAULT 0,
  device TEXT,
  parent_id BIGINT REFERENCES guestbook(id) ON DELETE CASCADE,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. 创建管理员表
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT DEFAULT 'moderator',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. 启用行级安全（RLS）
ALTER TABLE guestbook ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- 4. 删除现有策略（避免重复）
DROP POLICY IF EXISTS "任何人都可以查看留言" ON guestbook;
DROP POLICY IF EXISTS "任何人都可以发表留言" ON guestbook;
DROP POLICY IF EXISTS "只有管理员可以删除留言" ON guestbook;
DROP POLICY IF EXISTS "只有管理员可以更新留言" ON guestbook;
DROP POLICY IF EXISTS "只有管理员可以查看管理员表" ON admins;

-- 5. 创建新策略
-- 任何人都可以查看留言
CREATE POLICY "任何人都可以查看留言" ON guestbook
  FOR SELECT USING (true);

-- 任何人都可以发表留言
CREATE POLICY "任何人都可以发表留言" ON guestbook
  FOR INSERT WITH CHECK (true);

-- 只有管理员可以删除留言
CREATE POLICY "只有管理员可以删除留言" ON guestbook
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM admins 
      WHERE admins.id = auth.uid()
    )
  );

-- 只有管理员可以更新留言（如点赞）
CREATE POLICY "只有管理员可以更新留言" ON guestbook
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM admins 
      WHERE admins.id = auth.uid()
    )
  ) WITH CHECK (true);

-- 只有管理员可以查看管理员表
CREATE POLICY "只有管理员可以查看管理员表" ON admins
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM admins a
      WHERE a.id = auth.uid()
    )
  );

-- 6. 创建索引优化查询
CREATE INDEX IF NOT EXISTS idx_guestbook_created_at ON guestbook(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_parent_id ON guestbook(parent_id);
CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
CREATE INDEX IF NOT EXISTS idx_guestbook_is_admin ON guestbook(is_admin);

-- 7. 创建管理员用户函数
CREATE OR REPLACE FUNCTION setup_admin_user(
  admin_email TEXT,
  admin_name TEXT DEFAULT '管理员',
  admin_role TEXT DEFAULT 'admin'
)
RETURNS TABLE (user_id UUID, user_email TEXT, setup_result TEXT) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  admin_uuid UUID;
BEGIN
  -- 检查用户是否存在
  SELECT id INTO admin_uuid 
  FROM auth.users 
  WHERE email = admin_email;
  
  -- 如果用户不存在，返回错误
  IF admin_uuid IS NULL THEN
    RETURN QUERY SELECT NULL::UUID, admin_email, '用户不存在，请先在Supabase Auth中创建用户';
    RETURN;
  END IF;
  
  -- 插入或更新admins表
  INSERT INTO admins (id, name, email, role)
  VALUES (admin_uuid, admin_name, admin_email, admin_role)
  ON CONFLICT (id) DO UPDATE 
  SET name = EXCLUDED.name, 
      email = EXCLUDED.email,
      role = EXCLUDED.role,
      updated_at = NOW();
  
  -- 返回结果
  RETURN QUERY SELECT admin_uuid, admin_email, '管理员设置成功';
END;
$$;

-- 8. 创建管理员操作日志表（可选）
CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  table_name TEXT,
  record_id TEXT,
  details JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 9. 创建操作日志函数
CREATE OR REPLACE FUNCTION log_admin_action()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO admin_logs (admin_id, action, table_name, record_id, details)
  VALUES (
    auth.uid(),
    TG_OP,
    TG_TABLE_NAME,
    CASE 
      WHEN TG_OP = 'DELETE' THEN OLD.id::TEXT
      ELSE NEW.id::TEXT
    END,
    CASE
      WHEN TG_OP = 'DELETE' THEN jsonb_build_object(
        'old_data', to_jsonb(OLD),
        'deleted_at', NOW()
      )
      WHEN TG_OP = 'INSERT' THEN jsonb_build_object(
        'new_data', to_jsonb(NEW)
      )
      WHEN TG_OP = 'UPDATE' THEN jsonb_build_object(
        'old_data', to_jsonb(OLD),
        'new_data', to_jsonb(NEW),
        'updated_at', NOW()
      )
    END
  );
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. 为guestbook表创建日志触发器
DROP TRIGGER IF EXISTS log_guestbook_admin_actions ON guestbook;
CREATE TRIGGER log_guestbook_admin_actions
AFTER INSERT OR UPDATE OR DELETE ON guestbook
FOR EACH ROW
EXECUTE FUNCTION log_admin_action();

-- 11. 使用说明注释
COMMENT ON TABLE guestbook IS '留言表，存储用户留言信息';
COMMENT ON TABLE admins IS '管理员表，存储管理员用户信息';
COMMENT ON TABLE admin_logs IS '管理员操作日志表，记录所有管理员操作';
COMMENT ON FUNCTION setup_admin_user IS '设置管理员用户函数，参数：admin_email(邮箱), admin_name(姓名), admin_role(角色)';

-- 12. 示例：设置管理员用户
-- 注意：需要先在Supabase Auth中创建用户，然后运行以下查询（取消注释并替换邮箱）
-- SELECT * FROM setup_admin_user('admin@yourdomain.com', '管理员', 'admin');

-- 13. 查看当前策略
SELECT 
  schemaname,
  tablename,
  policyname,
  permissive,
  roles,
  cmd,
  qual
FROM pg_policies 
WHERE schemaname = 'public' 
AND tablename IN ('guestbook', 'admins')
ORDER BY tablename, policyname;